Dev (#17)
* Meal deals (#5)

Meal deals implemented

* ops

* Update README.md

* Fixes, and suggestions. Search for TODO (#9)

* Feil safe (#7)

* fixes

* fix stringify

* fix

* fixes

* fixes

* fixes^fixes

* fixes^fixes2

* removed reward.js

* time (#10)

* time

* fix

* Update README.md

* Update README.md

* Time (#11)

* time

* fix

* put

* Coupon db (#14)

* GTD

* pathing fix

Error: SQLITE_ERROR: incomplete input

* Fixed nodejs package file

* CouponDB rev.

revidert

* Beehive

welcome to the Beehive

* beehive2

* sill a beehive

* Find curly braces

finding nemo

* tror jeg fant nemo

});

* text corrections

* README

les meg, da!

* null bug fix

replaced User with UserCoupouns

* Need more Logic and fix Test

* Almost logical

* URL's renamed to fit kebab-case

* update after merge

* expanded functions

unmerge functions plz

* frontend start

started != finished

* merge & debug?

* merge?

* Update .gitignore

* fix

* test

* mohahahaha

* stylesheet fix (#15)

ser bedre ut,

* fix

* hello

* Fixes (#16)

* JSON undefined @ updateCouponView();

funker på postman, men vil ikke JSON.parse this.responstext

* Fixed updateCouponView function, and Get

* fix

* test

* addDeal_400

json stemmer ikke, err: 400
sjekk console i web for json.

* fixed some ploblems with app.js

* we belive

* updateCoupons() undefined?

reward_footer: 120

* last