Coupon db (#14)
* GTD

* pathing fix

Error: SQLITE_ERROR: incomplete input

* Fixed nodejs package file

* CouponDB rev.

revidert

* Beehive

welcome to the Beehive

* beehive2

* sill a beehive

* Find curly braces

finding nemo

* tror jeg fant nemo

});

* text corrections

* README

les meg, da!

* null bug fix

replaced User with UserCoupouns

* Need more Logic and fix Test

* Almost logical

* URL's renamed to fit kebab-case

* update after merge

* expanded functions

unmerge functions plz

* frontend start

started != finished

* merge & debug?

* merge?

* Update .gitignore